// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	vfs_metadata "github.com/telnet2/mysql-vfs/services/metadata/internal/router/vfs/metadata"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	vfs_metadata.Register(r)
}
