// Code generated by hertz generator.

package metadata

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var (
	_ context.Context
	_ *app.RequestContext
	_ = consts.StatusOK
)
