// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	vfs_webhook "github.com/telnet2/mysql-vfs/services/webhook/internal/router/vfs/webhook"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	vfs_webhook.Register(r)
}
