// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"gocloud.dev/blob"
	_ "gocloud.dev/blob/fileblob"
	_ "gocloud.dev/blob/s3blob"

	"github.com/telnet2/mysql-vfs/internal/config"
	"github.com/telnet2/mysql-vfs/internal/serverutil"
	"github.com/telnet2/mysql-vfs/services/content/internal/app"
	"github.com/telnet2/mysql-vfs/services/content/internal/service"
)

func main() {
	settings := config.Load()

	ctx := context.Background()
	bucketURL := settings.BlobBucketURL()
	bucket, err := blob.OpenBucket(ctx, bucketURL)
	if err != nil {
		log.Fatalf("failed to open blob bucket: %v", err)
	}
	storage := service.NewStorageService(bucket, bucketURL, settings.InlineJSONMaxBytes(), settings.InlineJSONMediaTypes())

	app.SetDependencies(app.Dependencies{
		Bucket:  bucket,
		Config:  settings,
		Storage: storage,
	})

	address := settings.ServiceAddress("content")
	if address == "" {
		address = ":8082"
	}

	shutdownTimeout := 4 * time.Second
	h := server.New(
		server.WithHostPorts(address),
		server.WithExitWaitTime(shutdownTimeout),
		server.WithMaxRequestBodySize(50*1024*1024), // 50MB to support large file uploads
	)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		if err := bucket.Close(); err != nil {
			log.Printf("error closing bucket: %v", err)
		}
	})

	serverutil.SetupGracefulShutdown(h, shutdownTimeout, nil)

	register(h)
	h.Spin()
}
