// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/telnet2/mysql-vfs/internal/config"
	"github.com/telnet2/mysql-vfs/internal/db"
	"github.com/telnet2/mysql-vfs/services/scheduler/internal/app"
)

func main() {
	settings := config.Load()
	database, err := db.NewConnection(db.Config{
		User:     settings.MySQL.User,
		Password: settings.MySQL.Password,
		Host:     settings.MySQL.Host,
		Port:     settings.MySQL.Port,
		Database: settings.MySQL.Database,
		Params:   settings.MySQL.Params,
	})
	if err != nil {
		log.Fatalf("failed to connect database: %v", err)
	}

	app.SetDependencies(app.Dependencies{DB: database})

	h := server.New(server.WithHostPorts(settings.Server.Address))

	register(h)
	h.Spin()
}
