// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/telnet2/mysql-vfs/services/scheduler/internal/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	api := r.Group("/api/v1")
	api.POST("/cron", handler.RegisterCron)
	api.GET("/cron", handler.ListCrons)
	api.POST("/cron/:id/trigger", handler.TriggerCron)
}
