// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	vfs_scheduler "github.com/telnet2/mysql-vfs/services/scheduler/internal/router/vfs/scheduler"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	vfs_scheduler.Register(r)
}
