// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/telnet2/mysql-vfs/internal/config"
	"github.com/telnet2/mysql-vfs/internal/db"
	"github.com/telnet2/mysql-vfs/internal/serverutil"
	"github.com/telnet2/mysql-vfs/services/webhook/internal/app"
)

func main() {
	settings := config.Load()
	database, err := db.NewConnection(db.Config{
		User:     settings.MySQL.User,
		Password: settings.MySQL.Password,
		Host:     settings.MySQL.Host,
		Port:     settings.MySQL.Port,
		Database: settings.MySQL.Database,
		Params:   settings.MySQL.Params,
	})
	if err != nil {
		log.Fatalf("failed to connect database: %v", err)
	}

	app.SetDependencies(app.Dependencies{DB: database})

	address := settings.ServiceAddress("webhook")
	if address == "" {
		address = ":8084"
	}

	shutdownTimeout := 4 * time.Second
	h := server.New(
		server.WithHostPorts(address),
		server.WithExitWaitTime(shutdownTimeout),
	)

	if sqlDB, err := database.DB(); err == nil {
		h.Engine.OnShutdown = append(h.Engine.OnShutdown, func(ctx context.Context) {
			if cerr := sqlDB.Close(); cerr != nil {
				log.Printf("error closing webhook db: %v", cerr)
			}
		})
	}

	serverutil.SetupGracefulShutdown(h, shutdownTimeout, nil)

	register(h)
	h.Spin()
}
