// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/telnet2/mysql-vfs/services/webhook/internal/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	api := r.Group("/api/v1")
	api.POST("/configs", handler.CreateConfig)
	api.GET("/configs", handler.ListConfigs)
	api.POST("/deliveries/ack", handler.AckDelivery)
}
